### ISSUE TITLE
Move to bullet-db

### ISSUE THREAD

**Issue by akshaisarma** [bullet-db/ember-localforage#5]
Hello @Mogball, I am not sure if you want to maintain this repo anymore but since https://github.com/bullet-db/bullet-ui relies on this exclusively and we need to make some changes here, would you be willing to move this repo to there to let us maintain it going forward for continued development? 

If you want to make some changes for us, that's fine as well 😄

**Comment by Mogball** [comment]
I can't read JavaScript anymore, so she's all yours. How do I transfer the repo?

**Comment by akshaisarma** [comment]
Settings, scroll down, Danger Zone, transfer ownership to me and I'll move it to @bullet-db. If that doesn't work, I can add you to @bullet-db and you can transfer it directly

**Comment by Mogball** [comment]
Done. Good luck out there!

**Comment by akshaisarma** [comment]
@Mogball Hey again, can you transfer or make me the maintainer of the npm package: https://www.npmjs.com/package/ember-localforage as well? My npm username is `akshaisarma`

https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

**Comment by Mogball** [comment]
Done. I've added you as a maintainer.

**Comment by akshaisarma** [comment]
Thanks again!
